# -*- coding: utf-8 -*-
"""kakaocodingtest_인형뽑기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qSostv-MVcXwtOHj5Z217ouICMMDAMvY
"""

def solution(board, moves):
    goal = [] # 인형 통에 추가
    answer = 0 

    for i in moves:
        for k in range(len(board)): # 주어진 board의 행들, len 함수 써서 수로 뽑아내기 
            if board[k][i-1] != 0:  # 맨 위에서부터 0이 아닌 첫 수를 찾아냄 
                goal.append(board[k][i-1]) # 뽑은 인형 통에다가 append
                board[k][i-1] = 0 # 뽑은 인형 0으로 바꾸기

                if len(goal) > 1:  # 뽑은 인형이 2개 이상일 경우
                    if goal[-1] == goal[-2]: # 두 개가 같을 경우 빼주고 ... 
                        goal.pop(-1)
                        goal.pop(-1)
                        answer += 2    
                break

    return answer